version: "2.23.0"
services:
  mysqldb:
    container_name: mysql-nasko
    image: "mysql:latest"
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: naskoDB
      MYSQL_USER: nasko
      MYSQL_PASSWORD: nasko123
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - type: bind
        source: C:\Users\soft\Documents\dbvolume
        target: /var/lib/mysql
  api_service:
    container_name: springboot-nasko
    image: springboot-nasko
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysql-nasko:3306/naskoDB
    depends_on:
      - mysqldb
    volumes:
      - type: bind
        source: C:\Users\soft\Documents\dbvolume
        target: /var/lib/mysql




networks:
  springapimysql-net: